---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Run Docker Compose up
      become: yes
      shell: docker compose up --build -d
      args:
        executable: /bin/bash
        chdir: /home/qiross/code/TCC
