---
- name: Run Docker Compose
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Print current directory
      shell: |
        touch file.txt
      register: current_directory
      changed_when: false

    - name: Run Docker Compose up
      shell: docker compose -f /home/qiross/code/TCC/docker-compose.yml up --build -d
      args:
        executable: /bin/bash
